name: Build and Deploy

on:
  push:
    branches: ["main", "workflow-tests"]

jobs:
  build:
    name: build next and save artefact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: build next
        run: cd devnexus && npm i && npm run build
      - uses: actions/upload-artifact@v3
        with:
            name: gp2-frontend
            path: devnexus/.next/
    
  docker:
    name: build docker image and push to ghcr.io
    runs-on: ubuntu-latest
    needs: ["build"]

    steps:
        - uses: actions/checkout@v3
        - uses: actions/download-artifact@v3
          with:
            name: gp2-frontend
            path: devnexus/.next/
        - uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}
        - name: build the docker image
          run: cd infra docker compose build

        - name: push to ghcr.io
          run: docker push ghcr.io/ua92-devops-apprentices-org/gp2-frontend